import {
  api,
  client,
  getConfig,
  getEComStoresByFacility,
  getProductIdentificationPref,
  getUserPreference,
  hasError,
  fetchGoodIdentificationTypes,
  fetchProducts,
  initialise,
  logout,
  isError,
  Product,
  resetConfig,
  updateToken,
  updateInstanceUrl,
  setUserTimeZone,
  getAvailableTimeZones,
  getEComStores,
  setProductIdentificationPref,
  setUserPreference
} from '@hotwax/oms-api'

export {
  api,
  client,
  getConfig,
  getEComStoresByFacility,
  getProductIdentificationPref,
  getUserPreference,
  hasError,
  fetchGoodIdentificationTypes,
  fetchProducts,
  initialise,
  logout,
  isError,
  Product,
  resetConfig,
  updateToken,
  updateInstanceUrl,
  setUserTimeZone,
  getAvailableTimeZones,
  getEComStores,
  setProductIdentificationPref,
  setUserPreference
}